### ISSUE TITLE
--recurse-submodules unsupported mode

### ISSUE THREAD

**Issue by dpassen** [h/find-file-in-repository#22]
Looks like the `--recurse-submodules` flag is not compatible with `-zco`

```sh
$ git --version
git version 2.30.0

$ git ls-files --recurse-submodules -zco --exclude-standard
fatal: ls-files --recurse-submodules unsupported mode

$ git ls-files --recurse-submodules --exclude-standard
.gitignore
README.md
find-file-in-repository.el
```

**Comment by dpassen** [comment]
Bumping as this has been broken nearly a month with two different PRs to address.

**Comment by h** [comment]
Thanks for the bug report, Derek. This is now fixed by https://github.com/h/find-file-in-repository/pull/24

**Comment by dpassen** [comment]
Thank you. It's much appreciated!
