### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by Giiva4** [h/find-file-in-repository#28]

**Comment by Sushzhhz** [comment]
1. - ``

- [ ] ``1. [ ] ``_``_/

- [ ] 

> 

> 

- [ ] ``

- [ ] [](url)[](url)

**Comment by Sushzhhz** [comment]
/``- /``[](url)

> ****- > ****

- [ ] /[ ] /``__

> 

> ``****[](url)- > ``****[](url)****### ****__

- [ ] 1. [ ] 1. [ ] 1. [ ]

**Comment by pawakajay840-a11y** [comment]
https://github.com/h/find-file-in-repository/issues/28
