### ISSUE TITLE
Doesn't seem to work on windows

### ISSUE THREAD

**Issue by baztian** [h/find-file-in-repository#9]
When in a git repo (the non fallback case) find-file-in-repository doesn't seem to work. The minibuffer looks like this:

```
Find file in repository: [Das System kann den angegebenen Pfad nicht finden.
]
```

(My locale is german and it means the system is unable to find the path.)
I'm unable to open a file from this prompt.

**Comment by h** [comment]
Thanks for the bug report. This has been fixed by https://github.com/h/find-file-in-repository/pull/10/commits
